// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enemy.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Enemy {

  /// <summary>Holder for reflection information generated from enemy.proto</summary>
  public static partial class EnemyReflection {

    #region Descriptor
    /// <summary>File descriptor for enemy.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnemyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtlbmVteS5wcm90bxIFZW5lbXkaDGNvbW1vbi5wcm90byK3AgoLTW9uc3Rl",
            "ckJhc2USEgoKbW9uc3Rlcl9pZBgBIAEoCRIhCgR0eXBlGAIgASgOMhMuY29t",
            "bW9uLk1vbnN0ZXJUeXBlEhIKCmN1cnJlbnRfaHAYAyABKAUSDgoGbWF4X2hw",
            "GAQgASgFEhQKDGF0dGFja19wb3dlchgFIAEoBRIUCgxhdHRhY2tfc3BlZWQY",
            "BiABKAISEgoKbW92ZV9zcGVlZBgHIAEoAhINCgVwb3NfeBgIIAEoAhINCgVw",
            "b3NfeRgJIAEoAhINCgVwb3NfehgKIAEoAhIRCglkaXJlY3Rpb24YCyABKAIS",
            "FAoMYXR0YWNrX3JhbmdlGAwgASgCEiMKBXN0YXRlGA0gASgOMhQuY29tbW9u",
            "Lk1vbnN0ZXJTdGF0ZRISCgpleHBfcmV3YXJkGA4gASgFIl8KC01vdmVSZXF1",
            "ZXN0EhIKCm1vbnN0ZXJfaWQYASABKAkSEAoIdGFyZ2V0X3gYAiABKAISEAoI",
            "dGFyZ2V0X3kYAyABKAISGAoQc3BlZWRfbXVsdGlwbGllchgEIAEoAmIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Enemy.MonsterBase), global::Enemy.MonsterBase.Parser, new[]{ "MonsterId", "Type", "CurrentHp", "MaxHp", "AttackPower", "AttackSpeed", "MoveSpeed", "PosX", "PosY", "PosZ", "Direction", "AttackRange", "State", "ExpReward" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Enemy.MoveRequest), global::Enemy.MoveRequest.Parser, new[]{ "MonsterId", "TargetX", "TargetY", "SpeedMultiplier" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// enemy.proto
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MonsterBase : pb::IMessage<MonsterBase>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MonsterBase> _parser = new pb::MessageParser<MonsterBase>(() => new MonsterBase());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MonsterBase> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Enemy.EnemyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonsterBase() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonsterBase(MonsterBase other) : this() {
      monsterId_ = other.monsterId_;
      type_ = other.type_;
      currentHp_ = other.currentHp_;
      maxHp_ = other.maxHp_;
      attackPower_ = other.attackPower_;
      attackSpeed_ = other.attackSpeed_;
      moveSpeed_ = other.moveSpeed_;
      posX_ = other.posX_;
      posY_ = other.posY_;
      posZ_ = other.posZ_;
      direction_ = other.direction_;
      attackRange_ = other.attackRange_;
      state_ = other.state_;
      expReward_ = other.expReward_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonsterBase Clone() {
      return new MonsterBase(this);
    }

    /// <summary>Field number for the "monster_id" field.</summary>
    public const int MonsterIdFieldNumber = 1;
    private string monsterId_ = "";
    /// <summary>
    /// 怪物ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MonsterId {
      get { return monsterId_; }
      set {
        monsterId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::Common.MonsterType type_ = global::Common.MonsterType.ZombieBasic;
    /// <summary>
    /// 怪物类型（普通/BOSS）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Common.MonsterType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "current_hp" field.</summary>
    public const int CurrentHpFieldNumber = 3;
    private int currentHp_;
    /// <summary>
    /// 当前血量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CurrentHp {
      get { return currentHp_; }
      set {
        currentHp_ = value;
      }
    }

    /// <summary>Field number for the "max_hp" field.</summary>
    public const int MaxHpFieldNumber = 4;
    private int maxHp_;
    /// <summary>
    /// 最大血量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxHp {
      get { return maxHp_; }
      set {
        maxHp_ = value;
      }
    }

    /// <summary>Field number for the "attack_power" field.</summary>
    public const int AttackPowerFieldNumber = 5;
    private int attackPower_;
    /// <summary>
    /// 攻击力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AttackPower {
      get { return attackPower_; }
      set {
        attackPower_ = value;
      }
    }

    /// <summary>Field number for the "attack_speed" field.</summary>
    public const int AttackSpeedFieldNumber = 6;
    private float attackSpeed_;
    /// <summary>
    /// 攻击速度（秒）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float AttackSpeed {
      get { return attackSpeed_; }
      set {
        attackSpeed_ = value;
      }
    }

    /// <summary>Field number for the "move_speed" field.</summary>
    public const int MoveSpeedFieldNumber = 7;
    private float moveSpeed_;
    /// <summary>
    /// 移动速度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MoveSpeed {
      get { return moveSpeed_; }
      set {
        moveSpeed_ = value;
      }
    }

    /// <summary>Field number for the "pos_x" field.</summary>
    public const int PosXFieldNumber = 8;
    private float posX_;
    /// <summary>
    /// 位置X
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PosX {
      get { return posX_; }
      set {
        posX_ = value;
      }
    }

    /// <summary>Field number for the "pos_y" field.</summary>
    public const int PosYFieldNumber = 9;
    private float posY_;
    /// <summary>
    /// 位置Y
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PosY {
      get { return posY_; }
      set {
        posY_ = value;
      }
    }

    /// <summary>Field number for the "pos_z" field.</summary>
    public const int PosZFieldNumber = 10;
    private float posZ_;
    /// <summary>
    /// 位置Z
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PosZ {
      get { return posZ_; }
      set {
        posZ_ = value;
      }
    }

    /// <summary>Field number for the "direction" field.</summary>
    public const int DirectionFieldNumber = 11;
    private float direction_;
    /// <summary>
    /// 朝向角度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    /// <summary>Field number for the "attack_range" field.</summary>
    public const int AttackRangeFieldNumber = 12;
    private float attackRange_;
    /// <summary>
    /// 攻击范围
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float AttackRange {
      get { return attackRange_; }
      set {
        attackRange_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 13;
    private global::Common.MonsterState state_ = global::Common.MonsterState.MMove;
    /// <summary>
    /// 当前状态（如 STUNNED、DEAD）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Common.MonsterState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "exp_reward" field.</summary>
    public const int ExpRewardFieldNumber = 14;
    private int expReward_;
    /// <summary>
    /// 击杀获得经验
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ExpReward {
      get { return expReward_; }
      set {
        expReward_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MonsterBase);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MonsterBase other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MonsterId != other.MonsterId) return false;
      if (Type != other.Type) return false;
      if (CurrentHp != other.CurrentHp) return false;
      if (MaxHp != other.MaxHp) return false;
      if (AttackPower != other.AttackPower) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AttackSpeed, other.AttackSpeed)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MoveSpeed, other.MoveSpeed)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PosX, other.PosX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PosY, other.PosY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PosZ, other.PosZ)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Direction, other.Direction)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AttackRange, other.AttackRange)) return false;
      if (State != other.State) return false;
      if (ExpReward != other.ExpReward) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MonsterId.Length != 0) hash ^= MonsterId.GetHashCode();
      if (Type != global::Common.MonsterType.ZombieBasic) hash ^= Type.GetHashCode();
      if (CurrentHp != 0) hash ^= CurrentHp.GetHashCode();
      if (MaxHp != 0) hash ^= MaxHp.GetHashCode();
      if (AttackPower != 0) hash ^= AttackPower.GetHashCode();
      if (AttackSpeed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AttackSpeed);
      if (MoveSpeed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MoveSpeed);
      if (PosX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PosX);
      if (PosY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PosY);
      if (PosZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PosZ);
      if (Direction != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Direction);
      if (AttackRange != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AttackRange);
      if (State != global::Common.MonsterState.MMove) hash ^= State.GetHashCode();
      if (ExpReward != 0) hash ^= ExpReward.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MonsterId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MonsterId);
      }
      if (Type != global::Common.MonsterType.ZombieBasic) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (CurrentHp != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CurrentHp);
      }
      if (MaxHp != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(MaxHp);
      }
      if (AttackPower != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(AttackPower);
      }
      if (AttackSpeed != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(AttackSpeed);
      }
      if (MoveSpeed != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(MoveSpeed);
      }
      if (PosX != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(PosX);
      }
      if (PosY != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(PosY);
      }
      if (PosZ != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(PosZ);
      }
      if (Direction != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(Direction);
      }
      if (AttackRange != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(AttackRange);
      }
      if (State != global::Common.MonsterState.MMove) {
        output.WriteRawTag(104);
        output.WriteEnum((int) State);
      }
      if (ExpReward != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(ExpReward);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MonsterId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MonsterId);
      }
      if (Type != global::Common.MonsterType.ZombieBasic) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (CurrentHp != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CurrentHp);
      }
      if (MaxHp != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(MaxHp);
      }
      if (AttackPower != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(AttackPower);
      }
      if (AttackSpeed != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(AttackSpeed);
      }
      if (MoveSpeed != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(MoveSpeed);
      }
      if (PosX != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(PosX);
      }
      if (PosY != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(PosY);
      }
      if (PosZ != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(PosZ);
      }
      if (Direction != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(Direction);
      }
      if (AttackRange != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(AttackRange);
      }
      if (State != global::Common.MonsterState.MMove) {
        output.WriteRawTag(104);
        output.WriteEnum((int) State);
      }
      if (ExpReward != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(ExpReward);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MonsterId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MonsterId);
      }
      if (Type != global::Common.MonsterType.ZombieBasic) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (CurrentHp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrentHp);
      }
      if (MaxHp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxHp);
      }
      if (AttackPower != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttackPower);
      }
      if (AttackSpeed != 0F) {
        size += 1 + 4;
      }
      if (MoveSpeed != 0F) {
        size += 1 + 4;
      }
      if (PosX != 0F) {
        size += 1 + 4;
      }
      if (PosY != 0F) {
        size += 1 + 4;
      }
      if (PosZ != 0F) {
        size += 1 + 4;
      }
      if (Direction != 0F) {
        size += 1 + 4;
      }
      if (AttackRange != 0F) {
        size += 1 + 4;
      }
      if (State != global::Common.MonsterState.MMove) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (ExpReward != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExpReward);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MonsterBase other) {
      if (other == null) {
        return;
      }
      if (other.MonsterId.Length != 0) {
        MonsterId = other.MonsterId;
      }
      if (other.Type != global::Common.MonsterType.ZombieBasic) {
        Type = other.Type;
      }
      if (other.CurrentHp != 0) {
        CurrentHp = other.CurrentHp;
      }
      if (other.MaxHp != 0) {
        MaxHp = other.MaxHp;
      }
      if (other.AttackPower != 0) {
        AttackPower = other.AttackPower;
      }
      if (other.AttackSpeed != 0F) {
        AttackSpeed = other.AttackSpeed;
      }
      if (other.MoveSpeed != 0F) {
        MoveSpeed = other.MoveSpeed;
      }
      if (other.PosX != 0F) {
        PosX = other.PosX;
      }
      if (other.PosY != 0F) {
        PosY = other.PosY;
      }
      if (other.PosZ != 0F) {
        PosZ = other.PosZ;
      }
      if (other.Direction != 0F) {
        Direction = other.Direction;
      }
      if (other.AttackRange != 0F) {
        AttackRange = other.AttackRange;
      }
      if (other.State != global::Common.MonsterState.MMove) {
        State = other.State;
      }
      if (other.ExpReward != 0) {
        ExpReward = other.ExpReward;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MonsterId = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Common.MonsterType) input.ReadEnum();
            break;
          }
          case 24: {
            CurrentHp = input.ReadInt32();
            break;
          }
          case 32: {
            MaxHp = input.ReadInt32();
            break;
          }
          case 40: {
            AttackPower = input.ReadInt32();
            break;
          }
          case 53: {
            AttackSpeed = input.ReadFloat();
            break;
          }
          case 61: {
            MoveSpeed = input.ReadFloat();
            break;
          }
          case 69: {
            PosX = input.ReadFloat();
            break;
          }
          case 77: {
            PosY = input.ReadFloat();
            break;
          }
          case 85: {
            PosZ = input.ReadFloat();
            break;
          }
          case 93: {
            Direction = input.ReadFloat();
            break;
          }
          case 101: {
            AttackRange = input.ReadFloat();
            break;
          }
          case 104: {
            State = (global::Common.MonsterState) input.ReadEnum();
            break;
          }
          case 112: {
            ExpReward = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MonsterId = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Common.MonsterType) input.ReadEnum();
            break;
          }
          case 24: {
            CurrentHp = input.ReadInt32();
            break;
          }
          case 32: {
            MaxHp = input.ReadInt32();
            break;
          }
          case 40: {
            AttackPower = input.ReadInt32();
            break;
          }
          case 53: {
            AttackSpeed = input.ReadFloat();
            break;
          }
          case 61: {
            MoveSpeed = input.ReadFloat();
            break;
          }
          case 69: {
            PosX = input.ReadFloat();
            break;
          }
          case 77: {
            PosY = input.ReadFloat();
            break;
          }
          case 85: {
            PosZ = input.ReadFloat();
            break;
          }
          case 93: {
            Direction = input.ReadFloat();
            break;
          }
          case 101: {
            AttackRange = input.ReadFloat();
            break;
          }
          case 104: {
            State = (global::Common.MonsterState) input.ReadEnum();
            break;
          }
          case 112: {
            ExpReward = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 怪物移动请求（保留原有定义）
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MoveRequest : pb::IMessage<MoveRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MoveRequest> _parser = new pb::MessageParser<MoveRequest>(() => new MoveRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MoveRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Enemy.EnemyReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveRequest(MoveRequest other) : this() {
      monsterId_ = other.monsterId_;
      targetX_ = other.targetX_;
      targetY_ = other.targetY_;
      speedMultiplier_ = other.speedMultiplier_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveRequest Clone() {
      return new MoveRequest(this);
    }

    /// <summary>Field number for the "monster_id" field.</summary>
    public const int MonsterIdFieldNumber = 1;
    private string monsterId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MonsterId {
      get { return monsterId_; }
      set {
        monsterId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "target_x" field.</summary>
    public const int TargetXFieldNumber = 2;
    private float targetX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TargetX {
      get { return targetX_; }
      set {
        targetX_ = value;
      }
    }

    /// <summary>Field number for the "target_y" field.</summary>
    public const int TargetYFieldNumber = 3;
    private float targetY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TargetY {
      get { return targetY_; }
      set {
        targetY_ = value;
      }
    }

    /// <summary>Field number for the "speed_multiplier" field.</summary>
    public const int SpeedMultiplierFieldNumber = 4;
    private float speedMultiplier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float SpeedMultiplier {
      get { return speedMultiplier_; }
      set {
        speedMultiplier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MoveRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MoveRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MonsterId != other.MonsterId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TargetX, other.TargetX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TargetY, other.TargetY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SpeedMultiplier, other.SpeedMultiplier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MonsterId.Length != 0) hash ^= MonsterId.GetHashCode();
      if (TargetX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TargetX);
      if (TargetY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TargetY);
      if (SpeedMultiplier != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SpeedMultiplier);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MonsterId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MonsterId);
      }
      if (TargetX != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(TargetX);
      }
      if (TargetY != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(TargetY);
      }
      if (SpeedMultiplier != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(SpeedMultiplier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MonsterId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MonsterId);
      }
      if (TargetX != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(TargetX);
      }
      if (TargetY != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(TargetY);
      }
      if (SpeedMultiplier != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(SpeedMultiplier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MonsterId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MonsterId);
      }
      if (TargetX != 0F) {
        size += 1 + 4;
      }
      if (TargetY != 0F) {
        size += 1 + 4;
      }
      if (SpeedMultiplier != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MoveRequest other) {
      if (other == null) {
        return;
      }
      if (other.MonsterId.Length != 0) {
        MonsterId = other.MonsterId;
      }
      if (other.TargetX != 0F) {
        TargetX = other.TargetX;
      }
      if (other.TargetY != 0F) {
        TargetY = other.TargetY;
      }
      if (other.SpeedMultiplier != 0F) {
        SpeedMultiplier = other.SpeedMultiplier;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MonsterId = input.ReadString();
            break;
          }
          case 21: {
            TargetX = input.ReadFloat();
            break;
          }
          case 29: {
            TargetY = input.ReadFloat();
            break;
          }
          case 37: {
            SpeedMultiplier = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MonsterId = input.ReadString();
            break;
          }
          case 21: {
            TargetX = input.ReadFloat();
            break;
          }
          case 29: {
            TargetY = input.ReadFloat();
            break;
          }
          case 37: {
            SpeedMultiplier = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
