# scene.yaml
# scene.yaml
- scene_id: "forest_001"
  monsters:
    - monster_id: "zombie_001"
      type: 0  # ZOMBIE_BASIC
      current_hp: 50
      max_hp: 50
      attack_power: 10
      attack_speed: 1.5
      move_speed: 2.0
      pos_x: 100.0
      pos_y: 200.0
      pos_z: 0.0
      direction: 0.0
      attack_range: 5.0
      state: 0  # M_MOVE
      exp_reward: 10
    - monster_id: "zombie_002"
      type: 1  # ZOMBIE_FAST
      current_hp: 30
      max_hp: 30
      attack_power: 8
      attack_speed: 2.0
      move_speed: 3.5
      pos_x: 150.0
      pos_y: 210.0
      pos_z: 0.0
      direction: 1.57
      attack_range: 4.0
      state: 0  # M_MOVE
      exp_reward: 8
    - monster_id: "skeleton_001"
      type: 5  # SKELETON
      current_hp: 40
      max_hp: 40
      attack_power: 12
      attack_speed: 1.8
      move_speed: 2.5
      pos_x: 120.0
      pos_y: 220.0
      pos_z: 0.0
      direction: 0.785
      attack_range: 6.0
      state: 0  # M_MOVE
      exp_reward: 15

- scene_id: "forest_002"
  monsters:
    - monster_id: "zombie_tank_001"
      type: 2  # ZOMBIE_TANK
      current_hp: 100
      max_hp: 100
      attack_power: 15
      attack_speed: 1.0
      move_speed: 1.5
      pos_x: 300.0
      pos_y: 400.0
      pos_z: 0.0
      direction: 2.356
      attack_range: 3.0
      state: 0  # M_MOVE
      exp_reward: 25
    - monster_id: "zombie_explode_001"
      type: 3  # ZOMBIE_EXPLODE
      current_hp: 20
      max_hp: 20
      attack_power: 25
      attack_speed: 3.0
      move_speed: 2.0
      pos_x: 320.0
      pos_y: 420.0
      pos_z: 0.0
      direction: 3.14
      attack_range: 8.0
      state: 0  # M_MOVE
      exp_reward: 18
    - monster_id: "ghost_001"
      type: 6  # GHOST
      current_hp: 25
      max_hp: 25
      attack_power: 15
      attack_speed: 1.2
      move_speed: 4.0
      pos_x: 350.0
      pos_y: 410.0
      pos_z: 0.0
      direction: 0.0
      attack_range: 7.0
      state: 0  # M_MOVE
      exp_reward: 20

- scene_id: "dungeon_001"
  monsters:
    - monster_id: "zombie_boss_001"
      type: 4  # ZOMBIE_BOSS
      current_hp: 200
      max_hp: 200
      attack_power: 30
      attack_speed: 1.0
      move_speed: 1.0
      pos_x: 500.0
      pos_y: 600.0
      pos_z: 0.0
      direction: 1.57
      attack_range: 5.0
      state: 0  # M_MOVE
      exp_reward: 50
    - monster_id: "skeleton_002"
      type: 5  # SKELETON
      current_hp: 45
      max_hp: 45
      attack_power: 14
      attack_speed: 1.6
      move_speed: 2.8
      pos_x: 520.0
      pos_y: 610.0
      pos_z: 0.0
      direction: 0.785
      attack_range: 6.5
      state: 0  # M_MOVE
      exp_reward: 16
    - monster_id: "zombie_fast_003"
      type: 1  # ZOMBIE_FAST
      current_hp: 35
      max_hp: 35
      attack_power: 9
      attack_speed: 2.2
      move_speed: 4.0
      pos_x: 540.0
      pos_y: 590.0
      pos_z: 0.0
      direction: 3.14
      attack_range: 4.5
      state: 0  # M_MOVE
      exp_reward: 9

- scene_id: "cave_001"
  monsters:
    - monster_id: "zombie_tank_002"
      type: 2  # ZOMBIE_TANK
      current_hp: 120
      max_hp: 120
      attack_power: 18
      attack_speed: 1.0
      move_speed: 1.2
      pos_x: 700.0
      pos_y: 800.0
      pos_z: 0.0
      direction: 2.356
      attack_range: 3.5
      state: 0  # M_MOVE
      exp_reward: 30
    - monster_id: "zombie_explode_002"
      type: 3  # ZOMBIE_EXPLODE
      current_hp: 25
      max_hp: 25
      attack_power: 30
      attack_speed: 3.5
      move_speed: 1.8
      pos_x: 720.0
      pos_y: 820.0
      pos_z: 0.0
      direction: 0.0
      attack_range: 9.0
      state: 0  # M_MOVE
      exp_reward: 22
    - monster_id: "zombie_basic_003"
      type: 0  # ZOMBIE_BASIC
      current_hp: 60
      max_hp: 60
      attack_power: 12
      attack_speed: 1.4
      move_speed: 2.2
      pos_x: 740.0
      pos_y: 790.0
      pos_z: 0.0
      direction: 1.57
      attack_range: 5.5
      state: 0  # M_MOVE
      exp_reward: 12

- scene_id: "swamp_001"
  monsters:
    - monster_id: "zombie_boss_002"
      type: 4  # ZOMBIE_BOSS
      current_hp: 250
      max_hp: 250
      attack_power: 35
      attack_speed: 1.0
      move_speed: 0.8
      pos_x: 900.0
      pos_y: 1000.0
      pos_z: 0.0
      direction: 0.785
      attack_range: 6.0
      state: 0  # M_MOVE
      exp_reward: 60
    - monster_id: "skeleton_003"
      type: 5  # SKELETON
      current_hp: 50
      max_hp: 50
      attack_power: 16
      attack_speed: 1.7
      move_speed: 3.0
      pos_x: 920.0
      pos_y: 1010.0
      pos_z: 0.0
      direction: 3.14
      attack_range: 7.0
      state: 0  # M_MOVE
      exp_reward: 18
    - monster_id: "ghost_002"
      type: 6  # GHOST
      current_hp: 30
      max_hp: 30
      attack_power: 20
      attack_speed: 1.0
      move_speed: 4.5
      pos_x: 940.0
      pos_y: 990.0
      pos_z: 0.0
      direction: 2.356
      attack_range: 8.0
      state: 0  # M_MOVE
      exp_reward: 25

- scene_id: "volcano_001"
  monsters:
    - monster_id: "zombie_fire_001"
      type: 0  # ZOMBIE_BASIC (with fire element)
      current_hp: 70
      max_hp: 70
      attack_power: 15
      attack_speed: 1.6
      move_speed: 2.5
      pos_x: 1100.0
      pos_y: 1200.0
      pos_z: 0.0
      direction: 0.0
      attack_range: 6.0
      state: 0  # M_MOVE
      exp_reward: 20
    - monster_id: "zombie_tank_003"
      type: 2  # ZOMBIE_TANK
      current_hp: 150
      max_hp: 150
      attack_power: 25
      attack_speed: 1.0
      move_speed: 1.0
      pos_x: 1120.0
      pos_y: 1210.0
      pos_z: 0.0
      direction: 1.57
      attack_range: 4.0
      state: 0  # M_MOVE
      exp_reward: 35
    - monster_id: "zombie_explode_003"
      type: 3  # ZOMBIE_EXPLODE
      current_hp: 30
      max_hp: 30
      attack_power: 40
      attack_speed: 4.0
      move_speed: 1.5
      pos_x: 1140.0
      pos_y: 1190.0
      pos_z: 0.0
      direction: 3.14
      attack_range: 10.0
      state: 0  # M_MOVE
      exp_reward: 30

- scene_id: "ice_cavern_001"
  monsters:
    - monster_id: "zombie_ice_001"
      type: 0  # ZOMBIE_BASIC (with ice element)
      current_hp: 60
      max_hp: 60
      attack_power: 13
      attack_speed: 1.8
      move_speed: 2.0
      pos_x: 1300.0
      pos_y: 1400.0
      pos_z: 0.0
      direction: 0.785
      attack_range: 5.0
      state: 0  # M_MOVE
      exp_reward: 18
    - monster_id: "zombie_fast_004"
      type: 1  # ZOMBIE_FAST
      current_hp: 40
      max_hp: 40
      attack_power: 10
      attack_speed: 2.5
      move_speed: 5.0
      pos_x: 1320.0
      pos_y: 1410.0
      pos_z: 0.0
      direction: 2.356
      attack_range: 4.5
      state: 0  # M_MOVE
      exp_reward: 10
    - monster_id: "ghost_ice_001"
      type: 6  # GHOST (with ice element)
      current_hp: 35
      max_hp: 35
      attack_power: 22
      attack_speed: 1.2
      move_speed: 4.8
      pos_x: 1340.0
      pos_y: 1390.0
      pos_z: 0.0
      direction: 1.57
      attack_range: 8.0
      state: 0  # M_MOVE
      exp_reward: 30

- scene_id: "final_boss_001"
  monsters:
    - monster_id: "zombie_overlord_001"
      type: 4  # ZOMBIE_BOSS (Ultimate Form)
      current_hp: 500
      max_hp: 500
      attack_power: 50
      attack_speed: 1.0
      move_speed: 0.5
      pos_x: 1500.0
      pos_y: 1600.0
      pos_z: 0.0
      direction: 0.0
      attack_range: 10.0
      state: 0  # M_MOVE
      exp_reward: 100
    - monster_id: "skeleton_elite_001"
      type: 5  # SKELETON (Elite Variant)
      current_hp: 80
      max_hp: 80
      attack_power: 25
      attack_speed: 1.5
      move_speed: 3.5
      pos_x: 1520.0
      pos_y: 1610.0
      pos_z: 0.0
      direction: 1.57
      attack_range: 7.5
      state: 0  # M_MOVE
      exp_reward: 40
    - monster_id: "ghost_leader_001"
      type: 6  # GHOST (Boss Variant)
      current_hp: 60
      max_hp: 60
      attack_power: 35
      attack_speed: 1.0
      move_speed: 5.0
      pos_x: 1540.0
      pos_y: 1590.0
      pos_z: 0.0
      direction: 3.14
      attack_range: 12.0
      state: 0  # M_MOVE
      exp_reward: 50