# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: combat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ombat.proto\x12\x06\x63ombat\x1a\x0c\x63ommon.proto\"\x99\x01\n\rAttackRequest\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\'\n\x0b\x65ntity_type\x18\x02 \x01(\x0e\x32\x12.combat.EntityType\x12\x11\n\ttarget_id\x18\x03 \x01(\t\x12\x14\n\x0c\x61ttack_angle\x18\x04 \x01(\x02\x12\x10\n\x08skill_id\x18\x05 \x01(\t\x12\x11\n\tcast_time\x18\x06 \x01(\x02\"\xc0\x01\n\x08HitEvent\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\'\n\x0b\x65ntity_type\x18\x02 \x01(\x0e\x32\x12.combat.EntityType\x12\x13\n\x0b\x61ttacker_id\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x61mage\x18\x04 \x01(\x05\x12\"\n\nnew_status\x18\x05 \x01(\x0e\x32\x0e.common.Status\x12/\n\x11new_monster_state\x18\x06 \x01(\x0e\x32\x14.common.MonsterState*(\n\nEntityType\x12\r\n\tCHARACTER\x10\x00\x12\x0b\n\x07MONSTER\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'combat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENTITYTYPE._serialized_start=389
  _ENTITYTYPE._serialized_end=429
  _ATTACKREQUEST._serialized_start=39
  _ATTACKREQUEST._serialized_end=192
  _HITEVENT._serialized_start=195
  _HITEVENT._serialized_end=387
# @@protoc_insertion_point(module_scope)
