# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon*a\n\x0cMonsterState\x12\n\n\x06M_MOVE\x10\x00\x12\x0c\n\x08M_ATTACK\x10\x01\x12\r\n\tM_STUNNED\x10\x02\x12\x0c\n\x08M_SCARED\x10\x03\x12\n\n\x06M_DEAD\x10\x04\x12\x0e\n\nM_SPAWNING\x10\x05*\x7f\n\x0bMonsterType\x12\x10\n\x0cZOMBIE_BASIC\x10\x00\x12\x0f\n\x0bZOMBIE_FAST\x10\x01\x12\x0f\n\x0bZOMBIE_TANK\x10\x02\x12\x12\n\x0eZOMBIE_EXPLODE\x10\x03\x12\x0f\n\x0bZOMBIE_BOSS\x10\x04\x12\x0c\n\x08SKELETON\x10\x05\x12\t\n\x05GHOST\x10\x06*F\n\x06Status\x12\x08\n\x04IDLE\x10\x00\x12\x0b\n\x07\x43\x41STING\x10\x01\x12\x0b\n\x07STUNNED\x10\x02\x12\x08\n\x04\x44\x45\x41\x44\x10\x03\x12\x0e\n\nINVINCIBLE\x10\x04*<\n\x10StageSelectState\x12\x0b\n\x07PENDING\x10\x00\x12\r\n\tCONFIRMED\x10\x01\x12\x0c\n\x08REJECTED\x10\x02*I\n\x0b\x45lementType\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04\x46IRE\x10\x01\x12\t\n\x05WATER\x10\x02\x12\x07\n\x03ICE\x10\x03\x12\t\n\x05\x45\x41RTH\x10\x04\x12\x07\n\x03\x41IR\x10\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MONSTERSTATE._serialized_start=24
  _MONSTERSTATE._serialized_end=121
  _MONSTERTYPE._serialized_start=123
  _MONSTERTYPE._serialized_end=250
  _STATUS._serialized_start=252
  _STATUS._serialized_end=322
  _STAGESELECTSTATE._serialized_start=324
  _STAGESELECTSTATE._serialized_end=384
  _ELEMENTTYPE._serialized_start=386
  _ELEMENTTYPE._serialized_end=459
# @@protoc_insertion_point(module_scope)
