# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scene.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import combat_pb2 as combat__pb2
import broadcast_pb2 as broadcast__pb2
import enemy_pb2 as enemy__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bscene.proto\x12\x05scene\x1a\x0c\x63ombat.proto\x1a\x0f\x62roadcast.proto\x1a\x0b\x65nemy.proto\"\x9b\x01\n\x0bSceneUpdate\x12$\n\nhit_events\x18\x01 \x03(\x0b\x32\x10.combat.HitEvent\x12\x34\n\rattack_events\x18\x02 \x03(\x0b\x32\x1d.broadcast.EntityAttackNotify\x12\x30\n\x0chit_notifies\x18\x03 \x03(\x0b\x32\x1a.broadcast.EntityHitNotify\"C\n\tSceneData\x12\x10\n\x08scene_id\x18\x01 \x01(\t\x12$\n\x08monsters\x18\x02 \x03(\x0b\x32\x12.enemy.MonsterBaseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scene_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENEUPDATE._serialized_start=67
  _SCENEUPDATE._serialized_end=222
  _SCENEDATA._serialized_start=224
  _SCENEDATA._serialized_end=291
# @@protoc_insertion_point(module_scope)
