// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scene.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_scene_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_scene_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "combat.pb.h"
#include "broadcast.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_scene_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_scene_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_scene_2eproto;
namespace scene {
class SceneUpdate;
struct SceneUpdateDefaultTypeInternal;
extern SceneUpdateDefaultTypeInternal _SceneUpdate_default_instance_;
}  // namespace scene
PROTOBUF_NAMESPACE_OPEN
template<> ::scene::SceneUpdate* Arena::CreateMaybeMessage<::scene::SceneUpdate>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace scene {

// ===================================================================

class SceneUpdate final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:scene.SceneUpdate) */ {
 public:
  inline SceneUpdate() : SceneUpdate(nullptr) {}
  ~SceneUpdate() override;
  explicit PROTOBUF_CONSTEXPR SceneUpdate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SceneUpdate(const SceneUpdate& from);
  SceneUpdate(SceneUpdate&& from) noexcept
    : SceneUpdate() {
    *this = ::std::move(from);
  }

  inline SceneUpdate& operator=(const SceneUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline SceneUpdate& operator=(SceneUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SceneUpdate& default_instance() {
    return *internal_default_instance();
  }
  static inline const SceneUpdate* internal_default_instance() {
    return reinterpret_cast<const SceneUpdate*>(
               &_SceneUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SceneUpdate& a, SceneUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(SceneUpdate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SceneUpdate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SceneUpdate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SceneUpdate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SceneUpdate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SceneUpdate& from) {
    SceneUpdate::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SceneUpdate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "scene.SceneUpdate";
  }
  protected:
  explicit SceneUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHitEventsFieldNumber = 1,
    kAttackEventsFieldNumber = 2,
    kHitNotifiesFieldNumber = 3,
  };
  // repeated .combat.HitEvent hit_events = 1;
  int hit_events_size() const;
  private:
  int _internal_hit_events_size() const;
  public:
  void clear_hit_events();
  ::combat::HitEvent* mutable_hit_events(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::combat::HitEvent >*
      mutable_hit_events();
  private:
  const ::combat::HitEvent& _internal_hit_events(int index) const;
  ::combat::HitEvent* _internal_add_hit_events();
  public:
  const ::combat::HitEvent& hit_events(int index) const;
  ::combat::HitEvent* add_hit_events();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::combat::HitEvent >&
      hit_events() const;

  // repeated .broadcast.EntityAttackNotify attack_events = 2;
  int attack_events_size() const;
  private:
  int _internal_attack_events_size() const;
  public:
  void clear_attack_events();
  ::broadcast::EntityAttackNotify* mutable_attack_events(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::broadcast::EntityAttackNotify >*
      mutable_attack_events();
  private:
  const ::broadcast::EntityAttackNotify& _internal_attack_events(int index) const;
  ::broadcast::EntityAttackNotify* _internal_add_attack_events();
  public:
  const ::broadcast::EntityAttackNotify& attack_events(int index) const;
  ::broadcast::EntityAttackNotify* add_attack_events();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::broadcast::EntityAttackNotify >&
      attack_events() const;

  // repeated .broadcast.EntityHitNotify hit_notifies = 3;
  int hit_notifies_size() const;
  private:
  int _internal_hit_notifies_size() const;
  public:
  void clear_hit_notifies();
  ::broadcast::EntityHitNotify* mutable_hit_notifies(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::broadcast::EntityHitNotify >*
      mutable_hit_notifies();
  private:
  const ::broadcast::EntityHitNotify& _internal_hit_notifies(int index) const;
  ::broadcast::EntityHitNotify* _internal_add_hit_notifies();
  public:
  const ::broadcast::EntityHitNotify& hit_notifies(int index) const;
  ::broadcast::EntityHitNotify* add_hit_notifies();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::broadcast::EntityHitNotify >&
      hit_notifies() const;

  // @@protoc_insertion_point(class_scope:scene.SceneUpdate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::combat::HitEvent > hit_events_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::broadcast::EntityAttackNotify > attack_events_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::broadcast::EntityHitNotify > hit_notifies_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scene_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SceneUpdate

// repeated .combat.HitEvent hit_events = 1;
inline int SceneUpdate::_internal_hit_events_size() const {
  return _impl_.hit_events_.size();
}
inline int SceneUpdate::hit_events_size() const {
  return _internal_hit_events_size();
}
inline ::combat::HitEvent* SceneUpdate::mutable_hit_events(int index) {
  // @@protoc_insertion_point(field_mutable:scene.SceneUpdate.hit_events)
  return _impl_.hit_events_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::combat::HitEvent >*
SceneUpdate::mutable_hit_events() {
  // @@protoc_insertion_point(field_mutable_list:scene.SceneUpdate.hit_events)
  return &_impl_.hit_events_;
}
inline const ::combat::HitEvent& SceneUpdate::_internal_hit_events(int index) const {
  return _impl_.hit_events_.Get(index);
}
inline const ::combat::HitEvent& SceneUpdate::hit_events(int index) const {
  // @@protoc_insertion_point(field_get:scene.SceneUpdate.hit_events)
  return _internal_hit_events(index);
}
inline ::combat::HitEvent* SceneUpdate::_internal_add_hit_events() {
  return _impl_.hit_events_.Add();
}
inline ::combat::HitEvent* SceneUpdate::add_hit_events() {
  ::combat::HitEvent* _add = _internal_add_hit_events();
  // @@protoc_insertion_point(field_add:scene.SceneUpdate.hit_events)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::combat::HitEvent >&
SceneUpdate::hit_events() const {
  // @@protoc_insertion_point(field_list:scene.SceneUpdate.hit_events)
  return _impl_.hit_events_;
}

// repeated .broadcast.EntityAttackNotify attack_events = 2;
inline int SceneUpdate::_internal_attack_events_size() const {
  return _impl_.attack_events_.size();
}
inline int SceneUpdate::attack_events_size() const {
  return _internal_attack_events_size();
}
inline ::broadcast::EntityAttackNotify* SceneUpdate::mutable_attack_events(int index) {
  // @@protoc_insertion_point(field_mutable:scene.SceneUpdate.attack_events)
  return _impl_.attack_events_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::broadcast::EntityAttackNotify >*
SceneUpdate::mutable_attack_events() {
  // @@protoc_insertion_point(field_mutable_list:scene.SceneUpdate.attack_events)
  return &_impl_.attack_events_;
}
inline const ::broadcast::EntityAttackNotify& SceneUpdate::_internal_attack_events(int index) const {
  return _impl_.attack_events_.Get(index);
}
inline const ::broadcast::EntityAttackNotify& SceneUpdate::attack_events(int index) const {
  // @@protoc_insertion_point(field_get:scene.SceneUpdate.attack_events)
  return _internal_attack_events(index);
}
inline ::broadcast::EntityAttackNotify* SceneUpdate::_internal_add_attack_events() {
  return _impl_.attack_events_.Add();
}
inline ::broadcast::EntityAttackNotify* SceneUpdate::add_attack_events() {
  ::broadcast::EntityAttackNotify* _add = _internal_add_attack_events();
  // @@protoc_insertion_point(field_add:scene.SceneUpdate.attack_events)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::broadcast::EntityAttackNotify >&
SceneUpdate::attack_events() const {
  // @@protoc_insertion_point(field_list:scene.SceneUpdate.attack_events)
  return _impl_.attack_events_;
}

// repeated .broadcast.EntityHitNotify hit_notifies = 3;
inline int SceneUpdate::_internal_hit_notifies_size() const {
  return _impl_.hit_notifies_.size();
}
inline int SceneUpdate::hit_notifies_size() const {
  return _internal_hit_notifies_size();
}
inline ::broadcast::EntityHitNotify* SceneUpdate::mutable_hit_notifies(int index) {
  // @@protoc_insertion_point(field_mutable:scene.SceneUpdate.hit_notifies)
  return _impl_.hit_notifies_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::broadcast::EntityHitNotify >*
SceneUpdate::mutable_hit_notifies() {
  // @@protoc_insertion_point(field_mutable_list:scene.SceneUpdate.hit_notifies)
  return &_impl_.hit_notifies_;
}
inline const ::broadcast::EntityHitNotify& SceneUpdate::_internal_hit_notifies(int index) const {
  return _impl_.hit_notifies_.Get(index);
}
inline const ::broadcast::EntityHitNotify& SceneUpdate::hit_notifies(int index) const {
  // @@protoc_insertion_point(field_get:scene.SceneUpdate.hit_notifies)
  return _internal_hit_notifies(index);
}
inline ::broadcast::EntityHitNotify* SceneUpdate::_internal_add_hit_notifies() {
  return _impl_.hit_notifies_.Add();
}
inline ::broadcast::EntityHitNotify* SceneUpdate::add_hit_notifies() {
  ::broadcast::EntityHitNotify* _add = _internal_add_hit_notifies();
  // @@protoc_insertion_point(field_add:scene.SceneUpdate.hit_notifies)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::broadcast::EntityHitNotify >&
SceneUpdate::hit_notifies() const {
  // @@protoc_insertion_point(field_list:scene.SceneUpdate.hit_notifies)
  return _impl_.hit_notifies_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace scene

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_scene_2eproto
